import { createFileRoute, notFound } from "@tanstack/react-router";
import { ArrowRight, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Crumbs } from "@/components/page-hero";
import { courses, faqs } from "@/content/site";

export const Route = createFileRoute("/courses/$slug")({ loader: ({ params }) => { const course = courses.find((c) => c.slug === params.slug); if (!course) throw notFound(); return course; }, head: ({ loaderData }) => ({ meta: [{ title: `${loaderData?.title ?? "Science Course"} in Kharadi | Joshi’s Academy` }, { name: "description", content: loaderData?.description ?? "Science coaching at Joshi’s Academy." }, { property: "og:title", content: loaderData?.title ?? "Science Course" }, { property: "og:description", content: loaderData?.description ?? "Science coaching at Joshi’s Academy." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }], scripts: loaderData ? [{ type: "application/ld+json", children: JSON.stringify({ "@context":"https://schema.org", "@type":"Course", name:loaderData.title, description:loaderData.description, provider:{"@type":"EducationalOrganization",name:"Joshi’s Academy"}, educationalLevel:loaderData.className }) }] : [] }), component: Course });
function Course() { const c = Route.useLoaderData(); const open = () => window.dispatchEvent(new Event("open-enquiry")); return <><section className="bg-ink px-6 pb-24 pt-36 text-ivory md:px-10 md:pt-44"><div className="mx-auto max-w-[1500px]"><Crumbs items={["Courses", c.title]} /><p className="eyebrow mt-16 text-gold">{c.board} • {c.className}</p><h1 className="mt-6 max-w-5xl font-display text-6xl leading-[.92] md:text-9xl">{c.title}</h1><div className="mt-12 grid gap-8 border-t border-ivory/20 pt-8 md:grid-cols-2"><p className="max-w-xl text-lg leading-8 text-ivory/65">{c.description}</p><Button variant="hero" size="lg" className="justify-self-start md:justify-self-end" onClick={open}>Enquire about this course <ArrowRight /></Button></div></div></section><section className="section-shell grid gap-16 py-24 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow text-gold">Course overview</p><h2 className="mt-6 font-display text-5xl">For students ready to understand Science deeply.</h2></div><div className="space-y-14"><Block title="Who is this course for?">Students following the {c.board} {c.className} curriculum who want stronger concepts, regular practice and structured support throughout the academic year.</Block><Block title="Science curriculum"><div className="grid gap-6 sm:grid-cols-3">{["Physics","Chemistry","Biology"].map((x) => <div key={x} className="border-t border-gold pt-4"><h3 className="font-display text-2xl">{x}</h3><p className="mt-3 text-sm text-slate">Concepts, application and curriculum-aligned practice.</p></div>)}</div></Block><Block title="Teaching methodology"><List items={["Concept explanation before memorisation", "Structured notes for clear revision", "MCQs and application-based questions", "Small-batch discussion and personal attention"]} /></Block><Block title="Testing & doubt solving"><List items={["Regular chapter-wise testing", "Error analysis after assessment", "Dedicated doubt-solving support", "Board-oriented written practice"]} /></Block><Block title="Board preparation">Preparation progresses from conceptual clarity to timed practice, revision and confident written expression—without losing sight of why an answer works.</Block></div></section><section className="bg-muted py-24"><div className="section-shell"><p className="eyebrow text-gold">Course FAQs</p><div className="mt-10 max-w-4xl">{faqs.slice(0,5).map(([q,a]) => <details key={q} className="border-t border-border py-6"><summary className="cursor-pointer font-display text-2xl">{q}</summary><p className="pt-4 leading-7 text-slate">{a}</p></details>)}</div></div></section><section className="bg-ink py-24 text-ivory"><div className="section-shell flex flex-col justify-between gap-8 md:flex-row md:items-end"><h2 className="max-w-3xl font-display text-6xl">Start with a thoughtful conversation.</h2><Button variant="hero" size="lg" onClick={open}>Book free counselling <ArrowRight /></Button></div></section></>; }
function Block({ title, children }: { title:string; children:React.ReactNode }) { return <div className="border-t border-border pt-6"><h2 className="font-display text-3xl">{title}</h2><div className="mt-5 leading-7 text-slate">{children}</div></div>; }
function List({items}:{items:string[]}) { return <ul className="grid gap-4 sm:grid-cols-2">{items.map((x)=><li key={x} className="flex gap-3"><Check className="mt-1 size-4 shrink-0 text-gold" />{x}</li>)}</ul>; }